version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=hj9bmNqkUbEJb02hGoEQqAXGfwEX6
    ports:
      - "1433:1433"
    volumes:
        - ./data:/var/opt/mssql/data
        - ./log:/var/opt/mssql/log
        - ./secrets:/var/opt/mssql/secrets