spring:
  application:
    name: medical-appointment-api
  datasource:
    url: jdbc:sqlserver://elective2.database.windows.net:1433;databaseName=elective2-db;
    username: admin-elective2
    password: NKxfnD8X6ThBcm9gkyXwaXyjk4TzTTh8vThs58NecyFiBMxUC8vxDQGBT9ovM66Yx04TTguyQAryqAiG
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  servlet:
    context-path: /api
