name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # o 'adopt'

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        run: mvn clean install

      - name: List target directory
        run: ls -la target  # Listar archivos generados

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/medical-appointment-api-0.0.1-SNAPSHOT.jar  # Actualiza este patrón

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app

      - name: Deploy to Azure Spring Apps
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
          service-name: ${{ secrets.AZURE_SPRING_APPS_NAME }}
          app-name: medical-appointment-api
          package: target/medical-appointment-api-0.0.1-SNAPSHOT.jar  # Actualiza este nombre
